kotlin.code.style=official
kotlin.js.generate.executable.default=false
kotlin.mpp.applyDefaultHierarchyTemplate=true

kotlin.native.cacheKind=none
kotlin.apple.xcodeCompatibility.nowarn=true

android.useAndroidX=true
android.nonTransitiveRClass=true

# dokka v2 migration
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
