[versions]
kotlin-version = "1.9.10"
ktlint-version = "11.6.1"
detekt-version = "1.23.1"
dokka-version = "1.9.10"
kover-version = "0.7.4"

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-version" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt-version" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-version" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version"}
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover-version" }
